### ISSUE TITLE
[BUG] Pokemon Sapphire-Invalid system

### ISSUE THREAD

**Issue by gaster2411** [Cattn/gba#126]
**Describe the bug**
I went to pokemon sapphire on GBA. I copied the embed code and uploaded it to google sites, but it says invalid system upon launching

**To Reproduce**
1. Go to 'pokemonsapphire' on gba
2. Click on 'Get Embed Code!'
3. Copy the Embed Code
4. Upload to google sites
5. Click "Start game"
6. Invalid System appears

**Expected behavior**
The game opens like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/121835599/234125622-4a9c33de-7567-4fe2-b241-7f7faf5b40e0.png)

**Windows Or Chromebook?**
Chromebook

**Additional context**
none

**Comment by Cattn** [comment]
Thanks for bringing this to my attention! Can you share with me the embed code here, so I can check it out?

**Comment by gaster2411** [comment]
Alright, here is the embed code:
`<iframe src='https://math-study.github.io/gba/launchpad.html?gameID='1&gametitle=pokemonsapphire&fav=true width="100%" height="500" frameBorder="0" style="border: 0;"></iframe><br>Brought to you by <a href="https://math-study.github.io/gba" target="_blank">math-study.github.io/gba</a>`
The code didn't actually go into my clipboard, but a window popped up, with this code in it. I copy-pasted this code.
Also, the game works fine on the website, it only didn't work here.

**Comment by Cattn** [comment]
Should be fixed in https://github.com/Cattn/gba/commit/ff3dca4b8b4d48a64369fe2a5a369c4b0b5c1bac

thanks for the issue!

also your working code should be: 
`<iframe src='https://math-study.github.io/gba/launchpad.html?gameID=1&gametitle=pokemonsapphire&fav=true' width="100%" height="500" frameBorder="0" style="border: 0;"></iframe><br>Brought to you by <a href="https://math-study.github.io/gba" target="_blank">math-study.github.io/gba</a>`

**Comment by gaster2411** [comment]
ty

**Comment by Cattn** [comment]
Np!
